### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by ksl986735244** [amazon-research/spot-diff#1]
Why is there no pixel-level annotation in the Mask of this dataset?

**Comment by ksl986735244** [comment]
The pictures in the mask are all black.

**Comment by yzou2** [comment]
The downloaded masks have non-zero values with id2class mapping defined in
utils/id2class.py. You can load and check the values. As all these values
are low, so from first look, it's all black although. After running
prepare_data.py, the mask will be rescaled to binary mask of 0 and 255,
which you will see black and white colors in the masks.
