### ISSUE TITLE
A question about the experimental resolution

### ISSUE THREAD

**Issue by caoyunkang** [amazon-research/spot-diff#2]
Dear Authors,

Thanks for your great contribution to the anomaly detection community, and this paper will definitely bring a new prospect to relative research. 

However, I am wondering about the experimental resolution used in this paper. Generally, research about MVTec AD will use a resolution of 256x256 or 224x224, which is insufficient for practical application. The main reason is that the resolution for a practical production is usually very large, like the 6000x4000 RGB sensor you used in your research, to capture the tiny defects that potentially exist in the products.

Hence, the experimental resolution may be very crucial. I found the published images have a resolution of about 1500x1000. Is that your experimental resolution? Besides, can you share your original images in 6000x4000 resolution to further boost the research about the high-resolution anomaly detection problem?

Thanks a lot. Hope for your kind reply!

**Comment by yzou2** [comment]
Thanks for your interests in our work.

The provided dataset contains the images used in the paper. These images are cropped and downsampled version of the original 4kx6k resolution images to speed up model training and evaluation.

The original images contains lots of background. So cropping is helpful to boost the performances. But downsampling might hurt the performance a little bit. We can share the original dataset later.

Best,
Yang
