### ISSUE TITLE
Ground truth anomaly mask is missing 

### ISSUE THREAD

**Issue by Mugunthan98** [amazon-research/spot-diff#3]
Hi! Thank you for releasing this new industrial anomaly dataset.

I have downloaded this dataset using the provided link. 
[https://amazon-visual-anomaly.s3.us-west-2.amazonaws.com/VisA_20220922.tar](url)
But, I have observed that the ground truth masks for anomaly data is not visible.(I can only see a plain black background) 

Could please check this out?
Thanks in advance.

**Comment by yzou2** [comment]
This is a duplicate issue of https://github.com/amazon-science/spot-diff/issues/1#issuecomment-1255770483 

Hope the answer there can solve your problem.

Best,
Yang
