### ISSUE TITLE
Description of Anomaly classes especially PCB4 will be really helpful 

### ISSUE THREAD

**Issue by maulik-modi** [amazon-research/spot-diff#4]
Description of Anomaly classes especially PCB4 will be really helpful so that newbies in Electronic chip manufacturing domain can annotation image correctly and benchmark performance of different algorithms

**Comment by yzou2** [comment]
Check the defect types in here for all the subsets https://github.com/amazon-science/spot-diff/blob/main/utils/id2class.py

I try to use common language to describe the defects.
