### ISSUE TITLE
Strange label in some cases

### ISSUE THREAD

**Issue by cxcx1996** [amazon-research/spot-diff#7]
There are some strange labels on boundary, like capsules 052.png
![052](https://user-images.githubusercontent.com/67784047/216259183-699ebc27-3a27-4c24-aabb-cc021e1713b3.png)

Maybe it is caused by bilinear resize (instead nearest resize)? Could you please fix this problem and upload a new version?

**Comment by yzou2** [comment]
I have checked the 052 image. The image has defect types of (1) bubble (the red part in the mask); (2) leak (the blue part in the mask). I think it's a correct annotation. Can you elaborate why it is a incorrect annotation?
![Screen Shot 2023-02-05 at 4 57 22 PM](https://user-images.githubusercontent.com/20036855/216858393-46bacf6e-fc02-41cf-8a81-290f3019e33b.png)

**Comment by cxcx1996** [comment]
> I have checked the 052 image. The image has defect types of (1) bubble (the red part in the mask); (2) leak (the blue part in the mask). I think it's a correct annotation. Can you elaborate why it is a incorrect annotation? ![Screen Shot 2023-02-05 at 4 57 22 PM](https://user-images.githubusercontent.com/20036855/216858393-46bacf6e-fc02-41cf-8a81-290f3019e33b.png)

![20230206102443](https://user-images.githubusercontent.com/67784047/216869041-81cee404-ac25-435d-9552-2356bb50d63d.png)
You can focus on the boundary of the blue part. There are many tiny parts of strange colors include yellow, red and green.

**Comment by yzou2** [comment]
Sorry for the late response. Good catch and thanks a lot! I think this should not effect the 1-class and 2-class evaluation as the [prepare_data.py](https://github.com/amazon-science/spot-diff/blob/main/utils/prepare_data.py#L68) will binarize the maps. But I will regenerate the original data to remove such weird boundary for other use cases

**Comment by cxcx1996** [comment]
> Sorry for the late response. Good catch and thanks a lot! I think this should not effect the 1-class and 2-class evaluation as the [prepare_data.py](https://github.com/amazon-science/spot-diff/blob/main/utils/prepare_data.py#L68) will binarize the maps. But I will regenerate the original data to remove such weird boundary for other use cases

Thanks!
